[package]
name = "bevy_app_compute"
version = "0.12.1"
authors = ["Kjolnyr <kjolnyr@protonmail.com>"]
edition = "2021"
description = "App compute plugin for Bevy"
repository = "https://github.com/Kjolnyr/bevy_app_compute"
homepage = "https://github.com/Kjolnyr/bevy_app_compute"
documentation = "https://docs.rs/bevy_app_compute"
license = "MIT OR Apache-2.0"
readme = "README.md"
categories = ["game-development"]


[dependencies]
bevy = "0.12.1"
parking_lot = "0.12.1"
wgpu = { version = "0.17", features = ["naga"] }
codespan-reporting = "0.11.1"
futures-lite = "2.2.0"
bytemuck = "1.4.0"
naga = { version = "0.13.0", features = ["wgsl-in"] }
naga_oil = "0.10.1"

[dev-dependencies]
rand = "0.8.5"
bevy = { version = "0.12", features = ["wayland"] }

[[example]]
name = "simple"

[[example]]
name = "multi_pass"

[[example]]
name = "one_shot"

[[example]]
name = "boids"
